window.WISHLIST_DATA = {
  version: "2026-05-01-public-1",
  disclaimer: "",
  gifts: [
    {
      id: "gold-accessories",
      name: "Золотые аксессуары",
      link: "",
      price: "",
      comment: "Украшения или маленькие золотые детали, которые легко носить каждый день.",
      photo: "",
      variant: "wide",
      size: "normal",
      marked: false,
      createdAt: 1777482000000,
      updatedAt: 1777482000000,
    },
    {
      id: "leather-wallet-photo-window",
      name: "Кожаный кошелек с окошком для фото",
      link: "",
      price: "",
      comment: "Хочу кожаный кошелек, где есть прозрачная штучка для фотографии.",
      photo: "",
      variant: "ticket",
      size: "normal",
      marked: false,
      createdAt: 1777482001000,
      updatedAt: 1777482001000,
    },
    {
      id: "money",
      name: "Money",
      link: "",
      price: "",
      comment: "Деньги тоже отличный подарок.",
      photo: "",
      variant: "capsule",
      size: "normal",
      marked: false,
      createdAt: 1777482002000,
      updatedAt: 1777482002000,
    },
    {
      id: "beach-vibe-things",
      name: "Вещи с beach vibe",
      link: "",
      price: "",
      comment: "Все, что ощущается как пляж, солнце, море и отпуск.",
      photo: "",
      variant: "split",
      size: "large",
      marked: false,
      createdAt: 1777482003000,
      updatedAt: 1777482003000,
    },
    {
      id: "funko-pop",
      name: "Funko Pop",
      link: "",
      price: "",
      comment: "Фигурка Funko Pop из персонажей, которые мне могут понравиться.",
      photo: "",
      variant: "circle",
      size: "normal",
      marked: false,
      createdAt: 1777482004000,
      updatedAt: 1777482004000,
    },
    {
      id: "photo-locket-pendant",
      name: "Подвеска для фотографии",
      link: "",
      price: "",
      comment: "Подвеска, в которую можно запихнуть маленькую фотографию.",
      photo: "",
      variant: "oval",
      size: "normal",
      marked: false,
      createdAt: 1777482005000,
      updatedAt: 1777482005000,
    },
    {
      id: "marilyn-tshirt",
      name: "Конкретная футболка с Мэрилин",
      link: "",
      price: "",
      comment: "Та самая футболка с Мэрилин. Если есть ссылка или фото, можно добавить позже.",
      photo: "",
      variant: "slab",
      size: "large",
      marked: false,
      createdAt: 1777482006000,
      updatedAt: 1777482006000,
    },
    {
      id: "board-keychain",
      name: "Конкретный брелок с доской",
      link: "",
      price: "",
      comment: "Брелок с доской. Конкретную ссылку или картинку можно прикрепить потом.",
      photo: "",
      variant: "stamp",
      size: "normal",
      marked: false,
      createdAt: 1777482007000,
      updatedAt: 1777482007000,
    },
    {
      id: "jellycat-toy",
      name: "Игрушка Jellycat",
      link: "",
      price: "",
      comment: "Мягкая игрушка Jellycat.",
      photo: "",
      variant: "mini",
      size: "normal",
      marked: false,
      createdAt: 1777482008000,
      updatedAt: 1777482008000,
    },
    {
      id: "shared-activities",
      name: "Совместные активности",
      link: "",
      price: "",
      comment: "Разные активности вместе: куда-то сходить, что-то попробовать, устроить маленькое приключение.",
      photo: "",
      variant: "text",
      size: "large",
      marked: false,
      createdAt: 1777482009000,
      updatedAt: 1777482009000,
    },
    {
      id: "skincare",
      name: "Уходовая косметика",
      link: "",
      price: "",
      comment: "Косметика для ухода: приятная, полезная, красивая.",
      photo: "",
      variant: "wide",
      size: "normal",
      marked: false,
      createdAt: 1777482010000,
      updatedAt: 1777482010000,
    },
    {
      id: "surprise-me",
      name: "То, что вам кажется моим",
      link: "",
      price: "",
      comment: "Подарок, который вы сами подумаете, что мне бы понравился. Со звездочкой.",
      reservedText: "со звездочкой",
      photo: "",
      variant: "ticket",
      size: "large",
      marked: true,
      createdAt: 1777482011000,
      updatedAt: 1777482011000,
    },
  ],
};
